/****************************************************************************
 *
 * MODULE:       p.photomet
 * AUTHOR(S):    Yann Chemin - dr.yann.chemin@gmail.com
 * PURPOSE:      Apply photometric correction to a planetary raster map.
 *
 *               Corrects each pixel using:
 *                 output[s] = input[s] * f(0,0,0) / f(inc[s], emi[s], pha[s])
 *               where f is the chosen photometric model (Lambert, Minnaert,
 *               LunarLambert, HapkeHen, HapkeLeg, or LunarLambertMcEwen).
 *
 *               The incidence, emission and phase angle rasters are those
 *               generated by p.phocube.
 *
 * LICENSE:      The Unlicense - public domain dedication.
 *               SPDX-License-Identifier: Unlicense
 *               See https://unlicense.org for the full text and LICENSE
 *               file in this directory.
 *
 *****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include <grass/gis.h>
#include <grass/raster.h>
#include <grass/glocale.h>

#include "../../libs/p_photomodel/p_photomodel.h"

int main(int argc, char *argv[])
{
    struct GModule *module;
    struct Option  *opt_input, *opt_output, *opt_model;
    struct Option  *opt_incidence, *opt_emission, *opt_phase;
    struct Option  *opt_k, *opt_l, *opt_wh, *opt_hh, *opt_b0;
    struct Option  *opt_hg1, *opt_hg2, *opt_theta;
    struct Option  *opt_bh, *opt_ch;
    struct History  history;

    G_gisinit(argv[0]);

    module = G_define_module();
    G_add_keyword(_("Planetary"));
    G_add_keyword(_("Photometric Analysis"));
    G_add_keyword(_("photometry"));
    G_add_keyword(_("Hapke"));
    G_add_keyword(_("Minnaert"));
    module->label       = _("Apply photometric correction to a planetary raster.");
    module->description = _("Normalises a planetary raster to standard photometric "
                             "conditions (i=e=g=0) using per-pixel geometry backplanes "
                             "produced by p.phocube. Supported models: Lambert, "
                             "LommelSeeliger, LunarLambert, Minnaert, HapkeHen, "
                             "HapkeLeg, LunarLambertMcEwen.");

    opt_input = G_define_standard_option(G_OPT_R_INPUT);
    opt_output = G_define_standard_option(G_OPT_R_OUTPUT);

    opt_model = G_define_option();
    opt_model->key     = "model";
    opt_model->type    = TYPE_STRING;
    opt_model->required = YES;
    opt_model->options  = "lambert,lommelseeliger,lunarlambert,minnaert,"
                           "hapkehen,hapkeleg,lunarlambertmcewen";
    opt_model->answer   = "minnaert";
    opt_model->description = _("Photometric model");

    opt_incidence = G_define_standard_option(G_OPT_R_INPUT);
    opt_incidence->key = "incidence";
    opt_incidence->description = _("Incidence angle raster [degrees] from p.phocube");

    opt_emission = G_define_standard_option(G_OPT_R_INPUT);
    opt_emission->key = "emission";
    opt_emission->description = _("Emission angle raster [degrees] from p.phocube");

    opt_phase = G_define_standard_option(G_OPT_R_INPUT);
    opt_phase->key = "phase";
    opt_phase->description = _("Phase angle raster [degrees] from p.phocube");

    /* Model parameters */
    opt_k = G_define_option(); opt_k->key = "k"; opt_k->type = TYPE_DOUBLE;
    opt_k->required = NO; opt_k->answer = "1.0";
    opt_k->description = _("Minnaert exponent K [0.5–1.0] (Minnaert model)");

    opt_l = G_define_option(); opt_l->key = "l"; opt_l->type = TYPE_DOUBLE;
    opt_l->required = NO; opt_l->answer = "1.0";
    opt_l->description = _("LunarLambert mixing weight L [0–1]");

    opt_wh = G_define_option(); opt_wh->key = "wh"; opt_wh->type = TYPE_DOUBLE;
    opt_wh->required = NO; opt_wh->answer = "0.5";
    opt_wh->description = _("Hapke single-scatter albedo ω (0,1]");

    opt_hh = G_define_option(); opt_hh->key = "hh"; opt_hh->type = TYPE_DOUBLE;
    opt_hh->required = NO; opt_hh->answer = "0.0";
    opt_hh->description = _("Hapke opposition surge width h");

    opt_b0 = G_define_option(); opt_b0->key = "b0"; opt_b0->type = TYPE_DOUBLE;
    opt_b0->required = NO; opt_b0->answer = "0.0";
    opt_b0->description = _("Hapke opposition surge amplitude B₀");

    opt_hg1 = G_define_option(); opt_hg1->key = "hg1"; opt_hg1->type = TYPE_DOUBLE;
    opt_hg1->required = NO; opt_hg1->answer = "0.0";
    opt_hg1->description = _("Hapke HG asymmetry coeff hg1 (-1,1) (HapkeHen)");

    opt_hg2 = G_define_option(); opt_hg2->key = "hg2"; opt_hg2->type = TYPE_DOUBLE;
    opt_hg2->required = NO; opt_hg2->answer = "0.0";
    opt_hg2->description = _("Hapke HG 2nd coeff hg2 [0,1] (HapkeHen)");

    opt_theta = G_define_option(); opt_theta->key = "theta"; opt_theta->type = TYPE_DOUBLE;
    opt_theta->required = NO; opt_theta->answer = "0.0";
    opt_theta->description = _("Hapke macroscopic roughness angle Θ [0,90°]");

    opt_bh = G_define_option(); opt_bh->key = "bh"; opt_bh->type = TYPE_DOUBLE;
    opt_bh->required = NO; opt_bh->answer = "0.0";
    opt_bh->description = _("Hapke Legendre coeff b1 [-1,1] (HapkeLeg)");

    opt_ch = G_define_option(); opt_ch->key = "ch"; opt_ch->type = TYPE_DOUBLE;
    opt_ch->required = NO; opt_ch->answer = "0.0";
    opt_ch->description = _("Hapke Legendre coeff b2 [-1,1] (HapkeLeg)");

    if (G_parser(argc, argv))
        exit(EXIT_FAILURE);

    /* ---------------------------------------------------------------- */
    /* Build photometric model                                           */
    /* ---------------------------------------------------------------- */
    const char *model_name = opt_model->answer;
    PPhmParams params;
    PPhotoModelType mtype;

    if (strcmp(model_name, "lambert") == 0) {
        mtype = P_PHOTOMODEL_LAMBERT;
    } else if (strcmp(model_name, "lommelseeliger") == 0) {
        mtype = P_PHOTOMODEL_LOMMELSEELIGER;
    } else if (strcmp(model_name, "lunarlambert") == 0) {
        params.lunarlambert.L = atof(opt_l->answer);
        mtype = P_PHOTOMODEL_LUNARLAMBERT;
    } else if (strcmp(model_name, "minnaert") == 0) {
        params.minnaert.K = atof(opt_k->answer);
        mtype = P_PHOTOMODEL_MINNAERT;
    } else if (strcmp(model_name, "hapkehen") == 0) {
        params.hapke_hen.wh    = atof(opt_wh->answer);
        params.hapke_hen.hh    = atof(opt_hh->answer);
        params.hapke_hen.b0    = atof(opt_b0->answer);
        params.hapke_hen.hg1   = atof(opt_hg1->answer);
        params.hapke_hen.hg2   = atof(opt_hg2->answer);
        params.hapke_hen.theta = atof(opt_theta->answer);
        params.hapke_hen.zero_b0_std = 1;
        mtype = P_PHOTOMODEL_HAPKE_HEN;
    } else if (strcmp(model_name, "hapkeleg") == 0) {
        params.hapke_leg.wh    = atof(opt_wh->answer);
        params.hapke_leg.hh    = atof(opt_hh->answer);
        params.hapke_leg.b0    = atof(opt_b0->answer);
        params.hapke_leg.bh    = atof(opt_bh->answer);
        params.hapke_leg.ch    = atof(opt_ch->answer);
        params.hapke_leg.theta = atof(opt_theta->answer);
        params.hapke_leg.zero_b0_std = 1;
        mtype = P_PHOTOMODEL_HAPKE_LEG;
    } else { /* lunarlambertmcewen */
        mtype = P_PHOTOMODEL_LUNARLAMBERT_MCEWEN;
    }

    PPhotoModel *model = p_photomodel_create(mtype,
        (mtype == P_PHOTOMODEL_LAMBERT || mtype == P_PHOTOMODEL_LOMMELSEELIGER ||
         mtype == P_PHOTOMODEL_LUNARLAMBERT_MCEWEN) ? NULL : &params);
    if (!model)
        G_fatal_error(_("Cannot create photometric model '%s'"), model_name);

    double std_val = p_photomodel_standard(model);
    G_message(_("Model: %s  (standard value at nadir = %.6g)"),
               p_photomodel_name(model), std_val);

    /* ---------------------------------------------------------------- */
    /* Open input rasters                                                */
    /* ---------------------------------------------------------------- */
    int fd_in  = Rast_open_old(opt_input->answer, "");
    int fd_inc = Rast_open_old(opt_incidence->answer, "");
    int fd_emi = Rast_open_old(opt_emission->answer, "");
    int fd_pha = Rast_open_old(opt_phase->answer, "");
    int fd_out = Rast_open_new(opt_output->answer, DCELL_TYPE);

    struct Cell_head region;
    G_get_window(&region);
    int nrows = region.rows;
    int ncols = region.cols;

    DCELL *buf_in  = Rast_allocate_d_buf();
    DCELL *buf_inc = Rast_allocate_d_buf();
    DCELL *buf_emi = Rast_allocate_d_buf();
    DCELL *buf_pha = Rast_allocate_d_buf();
    DCELL *buf_out = Rast_allocate_d_buf();

    double *in_d   = (double *)G_malloc((size_t)ncols * sizeof(double));
    double *inc_d  = (double *)G_malloc((size_t)ncols * sizeof(double));
    double *emi_d  = (double *)G_malloc((size_t)ncols * sizeof(double));
    double *pha_d  = (double *)G_malloc((size_t)ncols * sizeof(double));
    double *out_d  = (double *)G_malloc((size_t)ncols * sizeof(double));

    for (int row = 0; row < nrows; row++) {
        G_percent(row, nrows, 2);
        Rast_get_d_row(fd_in,  buf_in,  row);
        Rast_get_d_row(fd_inc, buf_inc, row);
        Rast_get_d_row(fd_emi, buf_emi, row);
        Rast_get_d_row(fd_pha, buf_pha, row);

        /* Convert GRASS buffers to double[], propagating NULLs as NaN */
        for (int c = 0; c < ncols; c++) {
            in_d[c]  = Rast_is_d_null_value(&buf_in[c])  ? NAN : buf_in[c];
            inc_d[c] = Rast_is_d_null_value(&buf_inc[c]) ? NAN : buf_inc[c];
            emi_d[c] = Rast_is_d_null_value(&buf_emi[c]) ? NAN : buf_emi[c];
            pha_d[c] = Rast_is_d_null_value(&buf_pha[c]) ? NAN : buf_pha[c];
        }

        p_photomodel_apply_row(model, ncols, in_d, pha_d, inc_d, emi_d,
                                std_val, out_d);

        for (int c = 0; c < ncols; c++) {
            if (out_d[c] != out_d[c])
                Rast_set_d_null_value(&buf_out[c], 1);
            else
                buf_out[c] = (DCELL)out_d[c];
        }
        Rast_put_d_row(fd_out, buf_out);
    }
    G_percent(1, 1, 2);

    Rast_close(fd_in); Rast_close(fd_inc);
    Rast_close(fd_emi); Rast_close(fd_pha);
    Rast_close(fd_out);

    Rast_short_history(opt_output->answer, "raster", &history);
    Rast_command_history(&history);
    Rast_write_history(opt_output->answer, &history);

    G_free(in_d); G_free(inc_d); G_free(emi_d); G_free(pha_d); G_free(out_d);
    G_free(buf_in); G_free(buf_inc); G_free(buf_emi); G_free(buf_pha); G_free(buf_out);
    p_photomodel_free(model);

    G_message(_("Photometric correction complete: %s"), opt_output->answer);
    return EXIT_SUCCESS;
}
