/****************************************************************************
 * MODULE:       p.crater.draw (cl_kernels.c)
 * PURPOSE:      OpenCL kernel source for the DEM and image detectors.
 *               Kept as C string literals so the .deb does not need to
 *               ship a separate .cl file; the runtime compiles them
 *               via clCreateProgramWithSource at startup.
 *
 * AUTHOR(S):    Yann Chemin - dr.yann.chemin@gmail.com
 * LICENSE:      The Unlicense (SPDX-License-Identifier: Unlicense)
 ****************************************************************************/

#include "cl_kernels.h"

/* ------------------------------------------------------------------ */
/* DEM radial-profile detector. One work-item = one candidate centre   */
/* at one scale. The host enqueues a 2D NDRange over rows and cols at  */
/* a given scale r, swapping the radius and cos/sin tables per scale.  */
/*                                                                      */
/* Score formula mirrors detect_dem.c lines around the inner loop:      */
/*   signal = rim_mean - inner_mean                                     */
/*   score  = signal / (rim_std + 0.5)                                  */
/*   conf   = tanh(score / 3.0) when signal > 0, else 0                 */
/* ------------------------------------------------------------------ */
const char *p_crater_draw_cl_dem_src =
"__kernel void detect_dem_kernel(                                       \n"
"    __global const double *dem,                                        \n"
"    const int nrows,                                                   \n"
"    const int ncols,                                                   \n"
"    const double radius_px,                                            \n"
"    const int n_az,                                                    \n"
"    __global const double *cos_az,                                     \n"
"    __global const double *sin_az,                                     \n"
"    const double threshold,                                            \n"
"    __global double *conf_out)                                         \n"
"{                                                                      \n"
"    int col = get_global_id(0);                                        \n"
"    int row = get_global_id(1);                                        \n"
"    int ir  = (int)ceil(radius_px) + 1;                                \n"
"    int idx = row * ncols + col;                                       \n"
"    conf_out[idx] = 0.0;                                               \n"
"    if (row < ir || row >= nrows - ir) return;                         \n"
"    if (col < ir || col >= ncols - ir) return;                         \n"
"                                                                       \n"
"    double rim_sum = 0.0, rim_sq = 0.0, in_sum = 0.0;                  \n"
"    int n_rim = 0, n_in = 0;                                           \n"
"    for (int i = 0; i < n_az; i++) {                                   \n"
"        double rr = (double)row + radius_px * sin_az[i];               \n"
"        double cc = (double)col + radius_px * cos_az[i];               \n"
"        int r0 = (int)floor(rr), c0 = (int)floor(cc);                  \n"
"        int r1 = r0 + 1,         c1 = c0 + 1;                          \n"
"        if (r0 < 0 || r1 >= nrows || c0 < 0 || c1 >= ncols) continue;  \n"
"        double v00 = dem[r0 * ncols + c0];                             \n"
"        double v01 = dem[r0 * ncols + c1];                             \n"
"        double v10 = dem[r1 * ncols + c0];                             \n"
"        double v11 = dem[r1 * ncols + c1];                             \n"
"        if (isnan(v00) || isnan(v01) || isnan(v10) || isnan(v11))      \n"
"            continue;                                                  \n"
"        double dr = rr - (double)r0, dc = cc - (double)c0;             \n"
"        double v = (1.0-dr) * ((1.0-dc)*v00 + dc*v01)                  \n"
"                 +       dr * ((1.0-dc)*v10 + dc*v11);                 \n"
"        rim_sum += v; rim_sq += v * v; n_rim++;                        \n"
"                                                                       \n"
"        rr = (double)row + 0.5 * radius_px * sin_az[i];                \n"
"        cc = (double)col + 0.5 * radius_px * cos_az[i];                \n"
"        r0 = (int)floor(rr); c0 = (int)floor(cc);                      \n"
"        r1 = r0 + 1;         c1 = c0 + 1;                              \n"
"        if (r0 < 0 || r1 >= nrows || c0 < 0 || c1 >= ncols) continue;  \n"
"        v00 = dem[r0 * ncols + c0]; v01 = dem[r0 * ncols + c1];        \n"
"        v10 = dem[r1 * ncols + c0]; v11 = dem[r1 * ncols + c1];        \n"
"        if (isnan(v00) || isnan(v01) || isnan(v10) || isnan(v11))      \n"
"            continue;                                                  \n"
"        dr = rr - (double)r0; dc = cc - (double)c0;                    \n"
"        v = (1.0-dr) * ((1.0-dc)*v00 + dc*v01)                         \n"
"          +       dr * ((1.0-dc)*v10 + dc*v11);                        \n"
"        in_sum += v; n_in++;                                           \n"
"    }                                                                  \n"
"    if (n_rim < n_az / 2 || n_in < n_az / 4) return;                   \n"
"    double rim_mean = rim_sum / (double)n_rim;                         \n"
"    double in_mean  = in_sum  / (double)n_in;                          \n"
"    double rim_var  = rim_sq / (double)n_rim - rim_mean * rim_mean;    \n"
"    if (rim_var < 0.0) rim_var = 0.0;                                  \n"
"    double rim_std  = sqrt(rim_var);                                   \n"
"    double signal   = rim_mean - in_mean;                              \n"
"    if (signal <= 0.0) return;                                         \n"
"    double score = signal / (rim_std + 0.5);                           \n"
"    double conf  = tanh(score / 3.0);                                  \n"
"    if (conf < threshold) return;                                      \n"
"    conf_out[idx] = conf;                                              \n"
"}                                                                      \n";

/* ------------------------------------------------------------------ */
/* Image sun-shadow paired-arc detector. Mirrors detect_image.c.       */
/* Same kernel layout: 2D NDRange (col, row), one work item per       */
/* candidate centre. The host pre-computes the two arc tables for     */
/* the rotation set by the sun azimuth, plus the inner-disk samples.  */
/* ------------------------------------------------------------------ */
const char *p_crater_draw_cl_image_src =
"__kernel void detect_image_kernel(                                     \n"
"    __global const double *img,                                        \n"
"    const int nrows,                                                   \n"
"    const int ncols,                                                   \n"
"    const double radius_px,                                            \n"
"    const int n_arc,                                                   \n"
"    __global const double *cos_b,                                      \n"
"    __global const double *sin_b,                                      \n"
"    __global const double *cos_d,                                      \n"
"    __global const double *sin_d,                                      \n"
"    __global const double *cos_in,                                     \n"
"    __global const double *sin_in,                                     \n"
"    const double threshold,                                            \n"
"    __global double *conf_out)                                         \n"
"{                                                                      \n"
"    int col = get_global_id(0);                                        \n"
"    int row = get_global_id(1);                                        \n"
"    int ir  = (int)ceil(radius_px) + 1;                                \n"
"    int idx = row * ncols + col;                                       \n"
"    conf_out[idx] = 0.0;                                               \n"
"    if (row < ir || row >= nrows - ir) return;                         \n"
"    if (col < ir || col >= ncols - ir) return;                         \n"
"                                                                       \n"
"    double bsum = 0.0, dsum = 0.0, isum = 0.0;                         \n"
"    int nb = 0, nd = 0, ni = 0;                                        \n"
"    double allsum = 0.0, allsq = 0.0;                                  \n"
"    int nall = 0;                                                      \n"
"                                                                       \n"
"    for (int i = 0; i < n_arc; i++) {                                  \n"
"        /* Bright arc sample */                                        \n"
"        double rr = (double)row + radius_px * sin_b[i];                \n"
"        double cc = (double)col + radius_px * cos_b[i];                \n"
"        int r0 = (int)floor(rr), c0 = (int)floor(cc);                  \n"
"        int r1 = r0+1, c1 = c0+1;                                      \n"
"        if (r0>=0 && r1<nrows && c0>=0 && c1<ncols) {                  \n"
"            double v00 = img[r0*ncols+c0], v01 = img[r0*ncols+c1];     \n"
"            double v10 = img[r1*ncols+c0], v11 = img[r1*ncols+c1];     \n"
"            if (!(isnan(v00)||isnan(v01)||isnan(v10)||isnan(v11))) {   \n"
"                double dr = rr - (double)r0, dc = cc - (double)c0;     \n"
"                double v = (1.0-dr)*((1.0-dc)*v00+dc*v01)              \n"
"                         +       dr *((1.0-dc)*v10+dc*v11);            \n"
"                bsum += v; nb++; allsum += v; allsq += v*v; nall++;    \n"
"            }                                                          \n"
"        }                                                              \n"
"        /* Dark arc sample */                                          \n"
"        rr = (double)row + radius_px * sin_d[i];                       \n"
"        cc = (double)col + radius_px * cos_d[i];                       \n"
"        r0 = (int)floor(rr); c0 = (int)floor(cc);                      \n"
"        r1 = r0+1; c1 = c0+1;                                          \n"
"        if (r0>=0 && r1<nrows && c0>=0 && c1<ncols) {                  \n"
"            double v00 = img[r0*ncols+c0], v01 = img[r0*ncols+c1];    \n"
"            double v10 = img[r1*ncols+c0], v11 = img[r1*ncols+c1];    \n"
"            if (!(isnan(v00)||isnan(v01)||isnan(v10)||isnan(v11))) {  \n"
"                double dr = rr - (double)r0, dc = cc - (double)c0;    \n"
"                double v = (1.0-dr)*((1.0-dc)*v00+dc*v01)             \n"
"                         +       dr *((1.0-dc)*v10+dc*v11);           \n"
"                dsum += v; nd++; allsum += v; allsq += v*v; nall++;   \n"
"            }                                                         \n"
"        }                                                             \n"
"    }                                                                 \n"
"    if (nb < n_arc / 2 || nd < n_arc / 2) return;                     \n"
"    for (int i = 0; i < 4; i++) {                                     \n"
"        double rr = (double)row + 0.4 * radius_px * sin_in[i];        \n"
"        double cc = (double)col + 0.4 * radius_px * cos_in[i];        \n"
"        int r0 = (int)floor(rr), c0 = (int)floor(cc);                 \n"
"        int r1 = r0+1, c1 = c0+1;                                     \n"
"        if (r0<0 || r1>=nrows || c0<0 || c1>=ncols) continue;         \n"
"        double v00 = img[r0*ncols+c0], v01 = img[r0*ncols+c1];        \n"
"        double v10 = img[r1*ncols+c0], v11 = img[r1*ncols+c1];        \n"
"        if (isnan(v00)||isnan(v01)||isnan(v10)||isnan(v11)) continue; \n"
"        double dr = rr - (double)r0, dc = cc - (double)c0;            \n"
"        double v = (1.0-dr)*((1.0-dc)*v00+dc*v01)                     \n"
"                 +       dr *((1.0-dc)*v10+dc*v11);                   \n"
"        isum += v; ni++;                                              \n"
"    }                                                                 \n"
"    if (ni < 2) return;                                               \n"
"    double bmean = bsum / (double)nb;                                 \n"
"    double dmean = dsum / (double)nd;                                 \n"
"    double imean = isum / (double)ni;                                 \n"
"    double allmean = allsum / (double)nall;                           \n"
"    double allvar  = allsq / (double)nall - allmean * allmean;        \n"
"    if (allvar < 0.0) allvar = 0.0;                                   \n"
"    double allstd = sqrt(allvar);                                     \n"
"    double s1 = (bmean - dmean) / (allstd + 1e-9);                    \n"
"    double s2 = (0.5 * (bmean + dmean) - imean) / (allstd + 1e-9);    \n"
"    double score = s1 + 0.5 * fmax(0.0, s2);                          \n"
"    if (score <= 0.0) return;                                         \n"
"    double conf = tanh(score / 3.0);                                  \n"
"    if (conf < threshold) return;                                     \n"
"    conf_out[idx] = conf;                                             \n"
"}                                                                     \n";
